SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SALES] (
		[ID]          [int] IDENTITY(1, 1) NOT NULL,
		[CUSTOMER_ID] [int] NOT NULL,
    [PRODUCT_ID]  [int] NOT NULL
)
GO
ALTER TABLE [dbo].[SALES]
	WITH CHECK
	ADD CONSTRAINT [OSFRK_SALES_CUSTOMER_CUSTOMER_ID]
	FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMER] ([ID])
ALTER TABLE [dbo].[SALES]
	CHECK CONSTRAINT [OSFRK_SALES_CUSTOMER_CUSTOMER_ID]
GO
ALTER TABLE [dbo].[SALES]
	WITH CHECK
	ADD CONSTRAINT [OSFRK_SALES_PRODUCT_PRODUCT_ID]
	FOREIGN KEY ([PRODUCT_ID]) REFERENCES [dbo].[PRODUCT] ([ID])
ALTER TABLE [dbo].[SALES]
	CHECK CONSTRAINT [OSFRK_SALES_PRODUCT_PRODUCT_ID]
GO
